### ISSUE TITLE
Hi , about setting up a mirror in China

### ISSUE THREAD

**Issue by anphorea** [cobalt232/blackberrymanager#1]
Glad you built this app to help android users using blackberry apps,
however the onedrive link can't be accessed in China mainland,
I'm thinking about setting up a mirror site on http://bbdev.cn/blackberrymanager
would you please re-build an apk for me?
Thanks

**Comment by anphorea** [comment]
http://bbdev.cn/blackberrymanager/updatelist.txt

**Comment by anphorea** [comment]
I've altered your apk to redirect to my url . http://bbdev.cn/blackberrymanager 
hope you don't mind

**Comment by cobalt232** [comment]
I'm fine with that. Just be sure to keep it updated.
