### ISSUE TITLE
[Comment] Works fine on lower resolution and on tablets

### ISSUE THREAD

**Issue by dutchscientist** [cobalt232/blackberrymanager#10]
The new version of the hub (August 3, 2016) works fine on my BQ A4.5 (lower screen resolution) and Nexus 7 2013 Mobile (tablet).

So the demands from Blackberry are not an absolute requirement?

**Comment by cobalt232** [comment]
Thanks for this feedback. The requirements are an official statement of BlackBerry. It may work on a device with other specs, but not guaranteed.
