### ISSUE TITLE
Latest updates do trial status, but can't pay subscription via Google Play

### ISSUE THREAD

**Issue by dutchscientist** [cobalt232/blackberrymanager#11]
The latest updates to 1.3.1 look fine, but now record the trial status of the apps, which the subscription can be paid for. Unfortunately, when installed on a phone/tablet not supported via Google Play, this means there is no way to pay for the subscription, even if I want to.

Is it possible to install the older versions of the software?

**Comment by dutchscientist** [comment]
Update: for my phone this is now resolved, as Blackberry seems to have removed the block on certain phones installing it. Hence I removed everything, and was able to install using the Google Play store.

Unfortunately that won't work on the tablet (Nexus 7 2013 Mobile) yet. Don't know whether this can be solved, or whether Blackbeery has to allow it in the future.

**Comment by cobalt232** [comment]
Tablets are not yet officially supported. Guess it's because of the Launcher. Let's see what BlackBerry comes up with in the next few months.

**Comment by dutchscientist** [comment]
For information, I am lucky as I updated them anyway, and although the Play Store still complains, it does accept that I have paid the subscription so I can use them anyway.

Thanks to your app, I have the best of both worlds. Much appreciated! :+1:
