### ISSUE TITLE
Xiaomi Mi Max install issue.

### ISSUE THREAD

**Issue by JohnPSM** [cobalt232/blackberrymanager#12]
I am unable to install. I am running Android 6.0.1. It asks for permission to install and never does... Anything I need to check?

**Comment by cobalt232** [comment]
Unable to install BlackBerry Manager? Or unable to install an app in BlackBerry Manager?

Can you install other apps that are not downloaded from Play Store?

**Comment by JohnPSM** [comment]
It wont allow the download to start... it appears at the bottom of the screen and when I say ok, nothing happens...
Sorry, I have been a BB user since the old blue ones with the Mike antennae... I feel like a dolt with the Android.... Infinite regards,
John McNeil

**Comment by JohnPSM** [comment]
Under Settings I have selected --->Additional settings>Privacy>Device Administration>Unknown sources>Allow.

Doesnt seem to work either....

**Comment by cobalt232** [comment]
Nice!
