### ISSUE TITLE
I am trying to run the hub, but it keeps telling me I need an update

### ISSUE THREAD

**Issue by JohnPSM** [cobalt232/blackberrymanager#13]
I am trying to run the hub, but it keeps telling me I need an update.  When I say Update. it takes me to the Playstore which has the Uninstall and Open options, but no update.  I also cannot purchase the App because it recognizes that it is installed outside the Playstore...
What can I do?

**Comment by cobalt232** [comment]
Install the apps only from BlackBerry Manager.
