### ISSUE TITLE
on key predictions

### ISSUE THREAD

**Issue by Mingomj** [cobalt232/blackberrymanager#14]
Hi, I want to repport an issue with on key predictions. It doesn't work on my zmeria z5 compact. I don't know if root is needed or it doesn't work at all. Thank you for response.

**Comment by Mingomj** [comment]
It's an issue with BlackBerry keyboard of course.

**Comment by cobalt232** [comment]
What is the issue?

**Comment by Mingomj** [comment]
The problem was that prediction was available only in line above keyboard not over keys. I had also turned on type by swiping. Those two functions don't work in same time which is understandable. Unfortunately I realised it just now. Sorry for unnecessary post.
