### ISSUE TITLE
With latest updates, Blackberry Hub services won't install?

### ISSUE THREAD

**Issue by dutchscientist** [cobalt232/blackberrymanager#15]
Blackberry Hub services won't install; it says it is available but the download fails. This is on a tablet where Google Play says "not available", which was not a problem with previous versions?

Everything is updated to the latest versions.

**Comment by cobalt232** [comment]
What country are you in?

**Comment by dutchscientist** [comment]
United Kingdom. I have been able to install using the repository, but the Hub crashes when I access the accounts in Settings.

**Comment by cobalt232** [comment]
It may be a tablet problem. They are not officially supported. I'm investigating the downloading problem. Guess it's a token refreshing issue.

**Comment by dutchscientist** [comment]
Thanks. It did work previously on that tablet, may be Blackberry has changed something. Hope it can be fixed, if not, bad luck for me!

(wish Blackberry would stop being silly about tablets)

**Comment by cobalt232** [comment]
Downloading problem has been fixed and an update for BlackBerry Manager is being pushed. Re-checkin in the top right menu after you updated the manager. Downloading should then work again. The tablet issue can't be fixed on my side, sorry.

**Comment by dutchscientist** [comment]
No worries about the tablet, thanks for all your efforts!

Arnoud
