### ISSUE TITLE
Cant allow the manager to use my information

### ISSUE THREAD

**Issue by Nakopa** [cobalt232/blackberrymanager#17]
So the following problem. I have installed the manager, granted it the three permission prompts and now the final one (which you can see in the screenshot) always returns and doesnt let me continue. Even if I deny it, it returns. For more information, im using miui8 with google play services installed

![screenshot_2016-12-26-17-03-53-311_com google android gms 1](https://cloud.githubusercontent.com/assets/11838104/21484105/c40a85e2-cb8d-11e6-8da1-acffdf7de1f8.png)

**Comment by cobalt232** [comment]
Can you post a logcat log?

**Comment by Nakopa** [comment]
I get a permission denied whenever I try "adb logcat -f thingy.txt

**Comment by Nakopa** [comment]
[2016-12-28-13-33-43[1].txt](https://github.com/cobalt232/blackberrymanager/files/675561/2016-12-28-13-33-43.1.txt)
I hope it contains what you need

**Comment by Nakopa** [comment]
Reinstalled Google Framework, gave permissions and now it works. Thanks :)
