### ISSUE TITLE
Question ❓ 

### ISSUE THREAD

**Issue by ikbb** [cobalt232/blackberrymanager#19]

**Comment by ikbb** [comment]
I have reg hub services installed on my pixel.  The ads are starting to come up now, so I wanted to switch to this option indefinitely.   Is it possible to export all my hub email accounts and import them into is version?

**Comment by cobalt232** [comment]
Unfortunately no. You must uninstall all BlackBerry apps that you downloaded from Play Store. All settings will be lost. Then install the apps from BlackBerry Manager and reconfigure your accounts and settings.
