### ISSUE TITLE
Blackberry Multi-Language KeyBoard

### ISSUE THREAD

**Issue by mgadda406** [cobalt232/blackberrymanager#2]
When please supporting Arabic languages as second languages in ( Blackberry keyboard Multi-Language ) .

**Comment by cobalt232** [comment]
You can download a modified version of BlackBerry Keyboard here:
https://www.mycloud.ch/s/#SD357A0E6981D57A193EFEA7AA8DFD24E218257E855C9133B4DDE5DB0D274601

Use the "LangSwitch" variant.

**Comment by mgadda406** [comment]
Thank you so much
