### ISSUE TITLE
[Hub] Email do not change sync timeframe

### ISSUE THREAD

**Issue by trumvip** [cobalt232/blackberrymanager#21]
Email sync timeframe disable

**Comment by cobalt232** [comment]
sorry, is that a question?

**Comment by trumvip** [comment]
Add Gmail  account‎ in bb hub not set sync timeframe, always defauft 7 day.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: cobalt232Sent: 20:20 Thứ ba, ngày 14 tháng ba năm 2017To: cobalt232/blackberrymanagerReply To: cobalt232/blackberrymanagerCc: trumvip; AuthorSubject: Re: [cobalt232/blackberrymanager] [Hub] Email do not change sync timeframe (#21)sorry, is that a question?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cobalt232/blackberrymanager","title":"cobalt232/blackberrymanager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cobalt232/blackberrymanager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cobalt232 in #21: sorry, is that a question?"}],"action":{"name":"View Issue","url":"https://github.com/cobalt232/blackberrymanager/issues/21#issuecomment-286418361"}}}

**Comment by cobalt232** [comment]
No issues here. Remove the account and add it again.

**Comment by trumvip** [comment]
Thanks! But i ‎do it more times. Device: mi4 lte ram 2gb.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: cobalt232Sent: 1:54 Thứ tư, ngày 15 tháng ba năm 2017To: cobalt232/blackberrymanagerReply To: cobalt232/blackberrymanager‎Cc: trumvip; AuthorSubject: Re: [cobalt232/blackberrymanager] [Hub] Email do not change sync timeframe (#21)No issues here. Remove the account and add it again.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cobalt232/blackberrymanager","title":"cobalt232/blackberrymanager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cobalt232/blackberrymanager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cobalt232 in #21: No issues here. Remove the account and add it again."}],"action":{"name":"View Issue","url":"https://github.com/cobalt232/blackberrymanager/issues/21#issuecomment-286524513"}}}
