### ISSUE TITLE
Errors updating BlackBerry Hub

### ISSUE THREAD

**Issue by cvcv01** [cobalt232/blackberrymanager#22]
Hi, I already have BlackBerry Hub installed with the BlackBerry Manager. But when I try to update it to latest version, I get the following errors:

Translation from french : Packet is in conflict with packet of the same name

When I do repair, I get this :Downloaded file appears to be damaged

I didnt really want to uninstall and reinstall again, but any suggestions?

Thanks
Chris

**Comment by cobalt232** [comment]
Clear the folder \BlackberryManager on your internal SD-CARD. Then remove existing hub and reinstall.

**Comment by cvcv01** [comment]
Will try this out, thanks for your help

**Comment by cvcv01** [comment]
Tried, uninstalled BlackBerry Hub and the same error appears: Downloaded file appears to be damaged.

:(

**Comment by cvcv01** [comment]
I also cleared the BlackBerry Manager folder

**Comment by cobalt232** [comment]
Did you install any BlackBerry  apps directly from Play Store? What Device are you using? (Type, Android version)

**Comment by cvcv01** [comment]
Hi Cobalt, I have a Nexus 6p with Android 7.1.2. I have Blackberry BBM installed. From Blackberry manager, I installed Blackberry Hub+ Services, Blackberry Launcher, Blackberry Password...

Is it possible Blackberry adds a protection on Blackberry Hub? not sure why I was able to install it months ago, but new updates and installs are not working.

**Comment by cobalt232** [comment]
Ok, I'll look into that. It looks like Android 7.1 is the reason.

**Comment by cobalt232** [comment]
Seems to be fixed, so closing.

**Comment by craigy1314** [comment]
Hi cobalt. Thanks for the apps had your bb10 apps also

Now have Nokia 8 Sirocco ru ming oreo
BBM won't install through BlackBerry manager and BlackBerry notes and tasks says BlackBerry Hub + requires update for apps to work. Click on update and it goes straight to Google play store but the apps already installed.

How do u fix this
Thanks again

**Comment by cobalt232** [comment]
Remove all BlackBerry apps and reinstall them with BlackBerry Manager. Do not run Hub Plus Services to install apps from there.
