### ISSUE TITLE
Hub doesn't show BBM messages

### ISSUE THREAD

**Issue by oddboy** [cobalt232/blackberrymanager#23]
Hi,

What a great project.  How can I support it?!

I was wondering if there's a way to get BBM messages to show in threads.  

Thanks!

Joel

**Comment by cobalt232** [comment]
Hi. I believe that it is not possible. You are using the patched version from the repo, right?

**Comment by cobalt232** [comment]
You can support the project with a donation. Coding support is currently not required.

**Comment by oddboy** [comment]
Hi,

Yes, using the patched Hub, and the native BBM for Android.

It's weird though.  I installed the native android slack App, and it integrated itself into hub.  Maybe I need to install BBM before hub so BBM is already on the device.

Thanks for the reply!   Great project!   Do you accept donations?

Joel

Sent via the BlackBerry Hub for Android<http://play.google.com/store/apps/details?id=com.blackberry.hub>
