### ISSUE TITLE
Update Privacy Shade vs Hub+ Services

### ISSUE THREAD

**Issue by Edward48** [cobalt232/blackberrymanager#25]
Hi cobalt232, thanx for all the work, I really appreciate it.

However, these days I am facing the following issue:
I am using especially the Privacy Shade and received yesterday a notification for update to v1.1.0.31.
However, after installing and opening the apk it requested me to install Hub+ Services as well.
I did this several times through BB Manager, no success.

In generally I did as follows:
I uninstalled all your software (Privacy Shade, Hub+ Services, and BB Manager).
Clean the device w/ CCleaner, then remove the BB Manager folder, then reboot the device.
Install first BB Manager, then Hub+ Service, last Privacy Shade.
Start Privacy Shade, receive message "Um dieses Programm verwenden zu können, müssen Sie zuerst Dienste des BB Hub+ aktualisieren".
Click "DEV IGNORE", give permission for Privacy Shade to overlay over other apps, then Privacy Shade Option Menu is displayed (Benachrichtigungen immer anzeigen, Lernprogramm anzeigen, Hilfe, Nutzungsbedingungen), choose "Benachrichtigung immer anzeigen", then push Privacy Shade in background (press home button), then call Privacy Shade w/ pull-down menu and receive a grey, non-clickable screen titled Privacy Shade.
No side bar for options is visable, only the full, grey screen.
That is the permanent appearance.
Rebooting the device and starting Privacy Shade displays again "Um dieses Programm...", clicking "DEV IGNORE" leads directly to the grey screen again.

Concerning the version before (1.0.0.12?), I had no issues with.
My device is Oneplus3 with Android 7.1.1. and OS 4.1.3. before and after update.

Do you have any suggestion how to overcome the matter?
If needed I can provide screen shots and offer assistance by testing any beta version on my device.

Cheers, Edward

**Comment by Edward48** [comment]
Needless to say: downloaded BB Manager from github; Hub+ and Privacy Shade w/in BB Manager.

**Comment by cobalt232** [comment]
Did you run Hub+ Services after installation and grant all permissions?

**Comment by Edward48** [comment]
Thnx for the prompt reply.
No, didn't do that before.
Therefore, uninstalled everything as written above.
Then reinstalled Hub+, run it and granted all permission requested (all in the app submenu plus notifications).
Then installed Privacy Shade, opened it, but the result is the same:
Receive message "Um dieses Programm verwenden zu können, müssen Sie zuerst Dienste des BB Hub+ aktualisieren".
Click "DEV IGNORE", give permission for Privacy Shade to overlay over other apps, then Privacy Shade Option Menu is displayed (Benachrichtigungen immer anzeigen, Lernprogramm anzeigen, Hilfe, Nutzungsbedingungen), choose "Benachrichtigung immer anzeigen", then push Privacy Shade in background (press home button), then call Privacy Shade w/ pull-down menu and receive a grey, non-clickable screen titled Privacy Shade.
No side bar for options is visable, only the full, grey screen.

Another restart of the device does not change the phenomenon.

Thus, one step closer, but still not reached the goal...

Anything else I missed and made wrong?

**Comment by cobalt232** [comment]
Something is wrong. The dev message should not appear. You did not run Hub+ Services and then install privacy shade from there, right?

**Comment by Edward48** [comment]
No, I installed Privacy Shade from BB Manager, not via Hub+. 
(Even do not see how to do that, when opening Hub+ through BB Manager, it brings me to the Settings menu directly.  There is no way of installing anything via Hub+ .)

FYI, the complete choices when starting Privacy Shade are "Aktualisieren / Abbrechen / Dev ignore".

**Comment by cobalt232** [comment]
That message indicates, that Hub+ Services either is not installed, or that is was not patched correctly. Remove all BlackBerry apps from your device. Then reboot. Then run BlackBerry Manager, slide in the left menu and choose "Repository". Install the app called com.blackberry.infrastructure.apk. Then install com.blackberry.privacyshade.apk. 

After that, run BlackBerry Manager and try to update these two apps.

**Comment by Edward48** [comment]
Thanx, will do so.
Just one comment before: When checking the content of Repository NOW, it see com.blackberry.infrastructure.apk (v1.5.0.43353), but not com.blackberry.privacyshade.apk.

The BB Manager I am using was downloaded via github v1.0.0.41

Anyway, will let you know on the progress.

**Comment by Edward48** [comment]
Did as suggested.
Reinstalled BB Manager from github.
Installed Hub+ from Repository w/in BB Manager.
Granted all permissions.

Installed Privacy Shade from the BB Manager directly, as it is not contained in the Repository.
Again, the option for DEV IGNORE popped up...
Also, the screen is remaining fully grey w/o menu bar at the right.

P.S. I ignored the option to upgrade Hub+ to v1.5.2.44782, that is displyed w/in BB Manager.
That was your intention, right?

**Comment by cobalt232** [comment]
Update all apps if BlackBerry Manager suggests to do.

**Comment by Edward48** [comment]
Did it.
First installed Hub+ from Repository, granted all permissions.
Then run suggested update w/in BB Manager and double-checked that all permission are still granted.
Then installed Privacy Shade w/in BB Manager and started it.
**Surprise, surprise, it works!!!**

Therefore, thanx a lot for all the effort and very prompt replies!

The only thing that puzzles me is, before your last reply I did exactly the same just out of curiosity, but it did not work!!!
The whole procedure was the same, incl. uninstall and cleaning steps.

Anyway, I am not arguing at all.
If you want me to verify something in return, pls feel free to ask and I will assist happily.

Merci vielmol.

**Comment by cobalt232** [comment]
Gärn gscheh.

**Comment by Edward48** [comment]
Sorry, have to come back to you w/ two minor issues I want to share:
a) After reboot, Privacy Shade does only start working when first opening Hub+ via BB Manager.
   If one goes directly to Privacy Shade, the same routine as before (IGNORE DEV etc.) is starting.
b) Even once Privacy Shade is working properly, the quick key in the Schnelleinstellungen remains inactive in either direction.

Jammern auf hohem Niveau...   ;-)

**Comment by cobalt232** [comment]
Maybe check your device/Android security settings. Can Hub+ Services autostart after a reboot? It looks like the services, especially the licensing and permissions service is not started.

**Comment by Edward48** [comment]
Now you got me, no idea how to do that.
I cannot find such possiblity for settings in my device.
At least I did not see in the settings, submenu security & finger prints, or submenu apps.
Also, my device is not rooted.

**Comment by cobalt232** [comment]
https://forums.oneplus.net/threads/apps-auto-launch-in-android-n.484674/

**Comment by Edward48** [comment]
Cheers!
I look in many other sites, but not the most obvious one...

Activated both Hub+ and Privacy Shade, now it's working fine.
Still, the quick key is not responsive.

Anyway, all fine w/ me! Thanx again and enjoy your WE.
