### ISSUE TITLE
Ability to add bb hub as App like brifing in samsung galaxy s7 swipe from left

### ISSUE THREAD

**Issue by T-REX-XP** [cobalt232/blackberrymanager#26]
Now we have some software like Brifing(from Flipboard) in SGS 7/edge that called from left swipe on home screen. Could you please add some provider/permission to current version on BB Hub for using her like Brifing App?? thanks
![screenshot](https://cloud.githubusercontent.com/assets/4560084/26551690/62930726-448c-11e7-8369-1d53860ff966.jpg)

**Comment by cobalt232** [comment]
Sorry, but I'm not intending to implement custom patches.
