### ISSUE TITLE
BlackBerry Keyboard unable to download auxiliary dictionarys

### ISSUE THREAD

**Issue by splatterb0y** [cobalt232/blackberrymanager#29]
It's not possible to create a multilingual keyboard in your modified Keyboard APK because the download of the auxiliary dictionarys over carrier network isn't working. 

Maybe you can give it a look and fix it, I would much appreciate.

**Comment by cobalt232** [comment]
Are we talking about the keyboard version 3.x? if yes, its a known bug. BlackBerry is working on a fix. The problem doesn't occour with keyboard 2.7 and the problem isn't related to the patching.

**Comment by cobalt232** [comment]
Blackberry has released a new beta version of the keyboard app. You can download it in the repository in BlackBerry Manager.
