### ISSUE TITLE
"To many requests" Message

### ISSUE THREAD

**Issue by nicolasprieto91** [cobalt232/blackberrymanager#3]
Some links of updatelist.txt are broken or blocked by onedrive. The app shows "To many requests" message.

**Comment by cobalt232** [comment]
OneDrive quota is exeeded. Need to find a new hoster. Will fix asap. Meanwhile, get the files here:
https://www.mycloud.ch/s/#SD357A0E6981D57A193EFEA7AA8DFD24E218257E855C9133B4DDE5DB0D274601

Folder LATEST contains the latest files for Android 6.0 (Marshmallow)
Folder RECENT contains the files for Android 5.x (Lollipop)
