### ISSUE TITLE
Whatsapp 

### ISSUE THREAD

**Issue by xnog** [cobalt232/blackberrymanager#30]
Hi, how can I see whatsapp messages in blackberry hub? I've just installed hub and they aren't arriving there. Thanks.

**Comment by cobalt232** [comment]
Hi. Actually it should just work. No special settings are required. Make sure that you have granted all permissions to BlackBerry Hub+ Services, especially the notification persmission. If that doesn't help, a reinstallation of whatsapp may help.

**Comment by xnog** [comment]
Thanks! Reinstall worked!
