### ISSUE TITLE
BlackBerry Manager Update Fails

### ISSUE THREAD

**Issue by zavdevgithub** [cobalt232/blackberrymanager#31]
When I open BlackBerry Manager it pops up wanting to update: 'An update is available for this app!'. It shows version 1.0.0.44 available. Selecting UPDATE throws an error: 'Unfortunately BlackBerry Manager has stopped'. Of course selecting Open app again just repeats the same problem.  Any way around this, besides a full reinstall?

**Comment by cobalt232** [comment]
Just remove BlackBerry Manager and redownload from this site. Your installed BlackBerry apps aren't affected by the reinstall.
