### ISSUE TITLE
File not available (Android 8.0 Oreo - OmniROM)

### ISSUE THREAD

**Issue by JakoobCZ** [cobalt232/blackberrymanager#33]
Hi,
I would like to report issue with BlackBerry Manager on Android 8.0 Oreo (nightly OmniROM on Find 7s). The manager itself installs fine, but can't download any app. It says "File not available"

Tested official Blackberry apps from Google Play and those work.

Anyway thanks for the great work! I hope this is just some small issue, which will be solved soon :)

**Comment by jeetunichani** [comment]
I am facing similar issue on my Oneplus3T, The file is available but the HUB keeps crashing stating Give permission to HUB to run in background, Cant find the option like I used to in 7.1.2, Great Work to bring the adfree BB apps on Android. Just Love it.

**Comment by cobalt232** [comment]
BlackBerry Manager has now been updated to work with Android Oreo.
