### ISSUE TITLE
Viewing glympse doesn't work in patched version of BBM

### ISSUE THREAD

**Issue by mitfry** [cobalt232/blackberrymanager#34]
Dear Cobalt,

I've been using my new Galaxy S8 for a couple of weeks now and only noticed it yesterday.. but the Glympse feature doesn't seem to work on the patched version of BBM. It does send the location just fine so the receiver has no problems if using the official version of BBM. However, when trying to view a user's glypmse location using a patched version of BBM the "map" stays empty or doesn't load at all.

Would you be able to look into this?

**Comment by cobalt232** [comment]
This is because the Glympse API key doesn't match with the patched signature. Sorry, but that's a known issue I currently can't fix.
