### ISSUE TITLE
Phoenix OS

### ISSUE THREAD

**Issue by iz0eyj** [cobalt232/blackberrymanager#35]
Hi Cobalt,
BB Manager don't work on Phoenix OS (Android 7.1.1 Desktop).
It seems that the app cannot contact the Play Store.

Thanx, Federico

![screenshot_2017-11-23-17-04-37](https://user-images.githubusercontent.com/6331284/33181501-bcdafe76-d070-11e7-9209-8be5f1ccfab9.jpg)

**Comment by cobalt232** [comment]
Should work now with BlackBerry Manager 1.0.0.46

**Comment by iz0eyj** [comment]
Hi Cobalt,
thanks for patch, but... login is OK but it is impossible to download/update because it hangs on "pending".

Thanks, Federico
![screenshot_2018-04-23-13-11-29](https://user-images.githubusercontent.com/6331284/39123590-8ffecf1e-46f8-11e8-992a-c6ed136fe14e.jpg)
