### ISSUE TITLE
More a request than an issue

### ISSUE THREAD

**Issue by jfowlie** [cobalt232/blackberrymanager#36]
It would be nice to get the Productivity Tab in the manager as well. I don't know my way around enough to get it installed myself, but I would be happy to assist in any way I can.

I can't believe how bad other keyboards seem compared to the BB keyboard. I was very happy to get this onto a Pixel2 that I am having to use for business testing.

Thanks for your hard work!
--James

**Comment by T-REX-XP** [comment]
If you have got Magisk, you can install it from topic https://forum.xda-developers.com/android/apps-games/port-apks-blackberry-priv-venice-t3244542/page94

**Comment by cobalt232** [comment]
I've been looking at the productive app. It won't work without root access, therefore I can't make it available in BlackBerry Manager. Sorry.
