### ISSUE TITLE
Password Keeper Backup passwork doesn't work

### ISSUE THREAD

**Issue by T-REX-XP** [cobalt232/blackberrymanager#37]
Hi. I have got issue with backup passwords features. After selecting Google account showing the toast error: Unable to turn on backup feature. Error code 10

Device s7edge. Os: 7.0

**Comment by cobalt232** [comment]
The password backup feature doesn't work. You can backup your passwords with the export feature. Automatic saving to the cloud is not available due to the changed app signature.
