### ISSUE TITLE
Bb keyboard on oneplus3 'app not inatalled' 

### ISSUE THREAD

**Issue by sid2040** [cobalt232/blackberrymanager#39]
Running Android 8.0 on oneplus3 and using bb manager tried installing bb keyboard. Says 'app not installed' error.

**Comment by cobalt232** [comment]
Can you post a logcat log?

**Comment by sid2040** [comment]
I don't know how to do it. Can you guide the easiest way?

**Comment by cobalt232** [comment]
You can use Minimal ADB: https://forum.xda-developers.com/showthread.php?t=2317790

To learn about the commands of Logcat: https://developer.android.com/studio/command-line/logcat.html

But before we start with logging: Did you verify that BlackBerry Manager has all permissions set?

**Comment by sid2040** [comment]
Yes permissions are given as able to install hub and BlackBerry hub+ services.

**Comment by cobalt232** [comment]
Then the log would be helpful.

**Comment by sid2040** [comment]
[logcat.docx](https://github.com/cobalt232/blackberrymanager/files/1638597/logcat.docx)

**Comment by cobalt232** [comment]
According to the log, the keyboard was not downloaded with blackberry manager. There is no logging of the download process. Also, there is no logging of the patching process. That's why it doesn't install.

Please do the following:

1. go to your local SD card to folder \blackberryManager and remove any apk that is found there
2. Start logging with ADB (with the settings that you have used in the previos log)
3. Run BlackBerry Manager and download the Keyboard. Wait until the installation fails
4. Stop logging and post the logfile again.

Thanks.

**Comment by sid2040** [comment]
Tired as you said. deleted everything and installed fresh. check now if its okay.
[logcat.docx](https://github.com/cobalt232/blackberrymanager/files/1641865/logcat.docx)

**Comment by sid2040** [comment]
i am on onelus 3 oxygen os beta 30. i tried on my wife's oneplus 5 oxygen os 5.0 and was able to install.

**Comment by cobalt232** [comment]
Thank you! I can now see the error in the log (located at position 01-18 01:39:08.954 in the log). For some unknown reason, the Manifest patch is not applied. I need to investigate. Meanwhile, you can install the keyboard from the repositiory. Swipe from left to right in BlackBerry Managerto open the options. Then choose repository to access the file repository with prepatched apps. The latest Keyboard has the version 3.1.0.13834.

**Comment by sid2040** [comment]
Ok thanks. Installed through the apk.

**Comment by sid2040** [comment]
I see that the repository version number is an older one? Is it? Or it is just the numbering.

**Comment by cobalt232** [comment]
The latest version in the repo is 3.1.0.13834.

**Comment by sid2040** [comment]
Is this solved?
