### ISSUE TITLE
Problem to download the apk's

### ISSUE THREAD

**Issue by rsancristobal** [cobalt232/blackberrymanager#4]
the one drive server is reporting an error with your links!

**Comment by KhaledAlQahtani** [comment]
Just curious, wouldnt it be possible to host the APK's on dropbox or something similar instead of one drive? It would be much appreciated if I can get this to work.

Tell me if you need anything.

**Comment by cobalt232** [comment]
Links are up again. Unfortunately, Dropbox does not provide enough bandwith for the downloads. Will try to find a better solution.

**Comment by anantbit** [comment]
Unable to install blackberry Services. Make something up

**Comment by cobalt232** [comment]
Sorry, my bad. There was a bug in the authentication method. Redownload the upated BlackBerry Manager (1.0.0.19). That should fix the problem. Be sure to grant all permissions.
