### ISSUE TITLE
Google play connection error in BlackBerry Manager

### ISSUE THREAD

**Issue by ndvn101092** [cobalt232/blackberrymanager#41]
Everytime I open BlackBerry Manager or check for update, I get this error "google play connection error"  at the end of my screen. I already try to uninstall BlackBerry Manager and reinstall but still the same result. Pls help!

**Comment by abhi218** [comment]
Hi I also had the same issue. I couldn't update to the latest version ( 1.0.047 ). It was giving me an error   " blackberry manager stopped" when I tried to install on the phone. Then I found a solution I was able to update it, Not through the update option from the phone but instead I downloaded the APK again the most recent one and I patched the latest APK with the older APK version on the phone and it clicked. hope this helps. Check this link below, it says it was updated 17 days go. The logo of the blackberry manager changes from black ( old ) to Blue ( New ).

https://github.com/cobalt232/blackberrymanager

**Comment by abhi218** [comment]
Please let me know if it has worked. thanks

**Comment by abhi218** [comment]
To make it simple,

Just remove BlackBerry Manager and redownload from this site ( Link provided above ). Your installed BlackBerry apps aren't affected by the reinstallation of BlackBerry Manager.

**Comment by ndvn101092** [comment]
Thank you abhi218 for your reply!

Unfortunately, I already switch from Note 5 to Keyone, so now I dont have to a device to test it.

**Comment by abhi218** [comment]
Cool !!  :). Now I hope you don't need a blackberry manager after all. ;)
