### ISSUE TITLE
keyboard 3.2 doesn't install "not compatible with your phone"

### ISSUE THREAD

**Issue by j-levy** [cobalt232/blackberrymanager#43]
Hello, 
I have a problem with the new version of BlackBerry keyboard 3.2, it doesn't install with the error "app not compatible with your phone"

I am not the single one having this problem, as shown here : https://forums.crackberry.com/showthread.php?t=1083176&p=13142622&viewfull=1#post13142622
Is there a way to rollback to 3.1before finding where the problem is ? 
Regards.

**Comment by cobalt232** [comment]
A fix is on its way.

**Comment by cobalt232** [comment]
Fixed. Run BlackBerry Manager to get the update.

**Comment by j-levy** [comment]
Thanks for the fix, works perfectly !
