### ISSUE TITLE
Blackberry keyboard language issue 

### ISSUE THREAD

**Issue by KojotMaciek** [cobalt232/blackberrymanager#44]
Hi,
I have a problem with languages for keyboard on two devices. I installed blackberry manager and next blackberry keyboard (from manager). I'm from Poland so I am trying to use Polish language. On Huawei P9 Lite (Android 7) I can see different languages in keyboard settings, I tried to use Polish but I am pretty sure that language pack is not downloaded. I do not have word hints above keys. Hints works with English.
On Xiaomi Mi6 (Android 8) I tried to make the same operation but I don't see any language to choose in keboard setting - blank space.
I wonder If these devices are blocked or something like that, or maybe there is a problem with language database, that's why I can not download them.
Any suggestions?
BR,
Maciek

**Comment by heretsch** [comment]
Hi, I have this same problem with BlackBerry Keyboard.
Can you create modified version of BlackBerry Keyboard Multi-Language with polish language please?

**Comment by heretsch** [comment]
BlackBerry has fixed the problem with downloaded pack of languages. Anyway if you can create keyboard multi-language with Polish language I would be grateful.

**Comment by cobalt232** [comment]
Did you follow the instructions for setting up the multi language keyboard?

1. configure a multi language keyboard in keyboard settings
2. save the config
3. in the next dialog, select the SECOND entry of your primary language and disable system language
4. save setting

**Comment by heretsch** [comment]
Yes I did but on Xiaomi Mi6 android 8 (custom rom from xiaomi.eu) I don't see any language to choose. This issue does not exist on android 7 (custom rom from xiaomi.eu) so probably it's problem of Android 8 from xiaomi.eu for Xiaomi Mi6 that's why maybe we can have keyboard multi-language with Polish without configure in keyboard settings.

**Comment by heretsch** [comment]
I need only two languages ​​Polish and English with the possibility of changing without configuration in the keyboard settings if it's possible

**Comment by cobalt232** [comment]
Sorry to hear that. It may be related to Oreo. BlackBerry will soon update their own devices to Oreo. Let's hope that the keyboard gets an update.

**Comment by heretsch** [comment]
Thank you for Answer.
BR

**Comment by KojotMaciek** [comment]
I am not sure that is related to Oreo. On Huawei Mate 10 Pro with Android 8.0.0 (security updates from January 2018) everything works fine.

**Comment by heretsch** [comment]
Is it possible to create a multi-language apk file with Polish?

**Comment by cobalt232** [comment]
Polish is already part of the keyboard app. On CrackBerry.com forums BlackBerry staff confirmed that there have been server issues in the last few days. Language download should now work again.

**Comment by heretsch** [comment]
Yes it works and is downloaded but I can't chose multi-language keyboard because I have no language list in settings.
