### ISSUE TITLE
Google play connection error

### ISSUE THREAD

**Issue by MyGreenBodhi** [cobalt232/blackberrymanager#45]
I have 2 Google Pixel 2 XLs. On one Blackberry manager works flawlessly, on the other I get Google play connection error. 
I uninstalled and reinstalled, did check in....and nothing seems to fix it

**Comment by cobalt232** [comment]
To fix it, proceed as follows:

1. uninstall BlackBerry Manager
2. remove the Google account from device
3. add the Google account again to device
4. install BlackBerry Manager

Please report if this works for you.

**Comment by lcrooks69** [comment]
Hi Cobalt232,

I can verify that your instructions work perfectly. Thank you so much!!!

**Comment by MyGreenBodhi** [comment]
Sorry for the delay, I was travelling, but when I got home I was able to use these instructions to fix it.

Thanks,

**Comment by cobalt232** [comment]
Perfect. Closed for now.
