### ISSUE TITLE
AFW or Google Enterprise

### ISSUE THREAD

**Issue by Homer76** [cobalt232/blackberrymanager#46]
Hi,
i have a problem if i had installed HUB+ in AFW over UEM 12.7.1 and will additionally install in private over your BlackBerry manager. I will become the error message not compatible or out of the playstore while download error code 505.

Is there any tricks to install on both sides?

Cheers

**Comment by cobalt232** [comment]
Anything that uses Hub+ Services can not be mixed. Either install all from BlackBerry Manager or all from Play Store.
