### ISSUE TITLE
Hub unable to connect to BBM

### ISSUE THREAD

**Issue by lnngo** [cobalt232/blackberrymanager#5]
Hi,

Love the app, works awesome! Downloaded and installed to my Moto G (3rd Gen) running Marshmallow but the hub doesn't seem to connect to BBM. I installed BBM before the hub so maybe that's it? I've uninstalled and reinstalled with no luck.

Not sure if anyone else is having this issue. Hoping to see it resolved I've missed my hub a lot!

**Comment by whasupyo** [comment]
I am having the same issue. I'm  using moto x play and have marshmallow. Hubb won't recognize bbm and can't add it

**Comment by cobalt232** [comment]
Uninstall existing BlackBerry Messenger and install the pre-patched version from the repository in BlackBerry Manager.

**Comment by lnngo** [comment]
Sorry I'm not sure if I'm crazy but I can't find BBM through blackberry manager

**Comment by cobalt232** [comment]
It's in the repository. Check the top right menu in BlackBerry Manager.

**Comment by soham2008xyz** [comment]
The pre-patched version of BBM in the repository fails to install on a Moto G (4th Gen) running Android 7. I have not installed any BB Apps from the Play Store previously. Latest version of BB Hub+ Services is installed via BB Manager. Screenshots attached.

![screenshot_20170415-121200](https://cloud.githubusercontent.com/assets/7334295/25061527/34190f36-21d6-11e7-9207-840277047ee2.png)
![screenshot_20170415-121222](https://cloud.githubusercontent.com/assets/7334295/25061528/38e3c088-21d6-11e7-81a5-bc2840dac834.png)
![screenshot_20170415-121246](https://cloud.githubusercontent.com/assets/7334295/25061532/3cd98ae2-21d6-11e7-839e-4c8c186f6ee0.png)

**Comment by cobalt232** [comment]
I'll update a new version today. Meanwhile, re-download the old one again. It looks like the apk is corrupted.

**Comment by soham2008xyz** [comment]
Re-downloading worked, thanks!

**Comment by cobalt232** [comment]
The new BBM version 3.3.2.31 is now available in the repository.
