### ISSUE TITLE
BlackBerry Hub+ Services not working since update

### ISSUE THREAD

**Issue by sonora16** [cobalt232/blackberrymanager#50]
Hi Cobalt232,
Since updating the update a few minutes ago (25/04/2018: 15.30pm), my android device will not show the hub any more and also I tried to repair the app but said there was no file available. So uninstalled the Hub+ Services app and tried to reinstall but again there is no file available to download. Now no Hub or the Hub+ Services. Where can I download the Hub+ Services app?
Cheers
sonora16

**Comment by cobalt232** [comment]
No more information provided, closing.
