### ISSUE TITLE
Blackberry Keyboard spell correction issues

### ISSUE THREAD

**Issue by lindaandjon** [cobalt232/blackberrymanager#52]
We are heaving issues with the keyboard spelling stains that'd appear on the space bar being really unhelpful.  We use BlackBerry managerial on two phones and bothered gave the same issues of strange word replacements.  Other- others or otherwise, that - that'll, and plenty more.  Seven unis talked, reinstalled, cleared user dictionary etc with no effect. I'm sure thistles (this) must be a BlackBerry issue bur (bit) (but) wondered in (if) you were aware of it and I'm (if) therefore (there) were any older versions on the keyboard we could've (could) loaded (load) .  Thanks for a great app too.

**Comment by cobalt232** [comment]
Hi and thanks for reporting the issues. There are multiple threads on the Crackberry forums about strange behavior of the keyboard. Actually, BlackBerry will have to fix this. Meanwhile try the beta release of the KB. You'll find it in the repository in BlackBerry Manager.

**Comment by cobalt232** [comment]
Also, read this post on Crackberry:
https://forums.crackberry.com/showthread.php?t=1150690
