### ISSUE TITLE
Bbm doesn't allow you to log in

### ISSUE THREAD

**Issue by robdob** [cobalt232/blackberrymanager#54]
Hi I installed your manager, firstly, thank you so much it works beautifully. I'm having an issue with the bbm . When I install it via your manager it never let's me login. It keeps giving me an error message,  if I install bbm from google play the it allows me tootogin but doesn't show bbm messages within the hub 

Is there a fix for this?   Thanks

**Comment by cobalt232** [comment]
Currently, there is no fix for this. I'll keep working on it.

**Comment by polytan02** [comment]
Hello, do we have a fix to log into bbm via blackberry manager? A new bbm version has been released.

Si far I cannot install bbm via the manager (it is not even listed). I'm on 1.0.0.53.

**Comment by cobalt232** [comment]
Fixed
