### ISSUE TITLE
BBM is missing from 1.0.0.53 of Blackberry Manager

### ISSUE THREAD

**Issue by whodatzinger** [cobalt232/blackberrymanager#57]
Hi Colbalt232,
Just updated Blackberry Manager to 1.0.0.53 and Blackberry Messenger is no longer listed for download or update. Is this no longer available through you?

**Comment by polytan02** [comment]
Same issue here

**Comment by mitfry** [comment]
Can confirm. Been like this for multiple weeks now. BBM is now starting to nag about updating and using an old version.

**Comment by MyGreenBodhi** [comment]
Same here

**Comment by mitfry** [comment]
Alright, thank you for answering Cobalt. In the meantime, can we somehow switch to the normal BBM without losing chat history etc?

**Comment by roblee1e06** [comment]
> Alright, thank you for answering Cobalt. In the meantime, can we somehow switch to the normal BBM without losing chat history etc?

Same question - I keep getting prompted to update BBM but Google Play does not show it as installed and it's not in the Updates list. There's an Uninstall button, but I don't want to do that without understanding the impacts. If I uninstall and reinstall from Play, do I end up with a different PIN than is currently assigned to my phone? What other effects would there be - as mitfry asks, what happens to chat history? 

BTW despite the above, I want to thank you very much for what you've done with BlackBerry Manager, it has made my transition from BB OS10 (I had a Z10 which I miss using very much) to Android (Moto G5 running Nougat) a much better experience.

**Comment by polytan02** [comment]
@cobalt232 any chance you will be able to sort this issue please?

**Comment by mitfry** [comment]
Hi Cobalt, 

Has there been any update on this issue, or at the very least, do you think it's possible to bypass the changes made to BBM at all?

December is always a busy month. If you feel you don't have enough time to dive into this issue, would you please assist me/us into switching to the regular BBM without losing our chat history? 

I'd like to thank you in advance.

**Comment by cobalt232** [comment]
BBM is back, but will be removed again end of May 2019, as Emtek has abandoned BBM consumer version.
