### ISSUE TITLE
BlackBerry Contacts Widgets

### ISSUE THREAD

**Issue by baseelo** [cobalt232/blackberrymanager#59]
On my BlackBerry Priv I am able to use the Contacts widgets to create one-touch Direct Dial and Direct Message shortcuts on the home screen.

These widgets are not available on the "patched" Contacts app for other Android handsets?

**Comment by cobalt232** [comment]
These shortcuts are a feature of BlackBerry Launcher. The contacts app doesn't have a widget as far as I know.
