### ISSUE TITLE
Contacts has stopped

### ISSUE THREAD

**Issue by kol13190** [cobalt232/blackberrymanager#6]
Calendar and Contacts from PRIV apps crash on HTC 10, using a custom ROM (Viper10/VenomRom). Other apps such as BBM, Keyboard, Launcher, Notes, Search, Services, Tasks and HUB all work consistently. 

Upon launch it will actively go through the intro and then upon entering the main app, I receive:

 'Unfortunately, Calendar has stopped.' 'Unfortunately, Contacts has stopped'

I have attempted to use the apps from the repository, both old and new, and the manager to install it. All App permissions are allowed as well. Any way to fix this?

![screenshot_20160711-012015](https://cloud.githubusercontent.com/assets/20391839/16720577/bdb89114-4705-11e6-9646-ce92a3eaedc4.png)
![screenshot_20160711-012419](https://cloud.githubusercontent.com/assets/20391839/16720765/706db7ca-4707-11e6-817f-700d312f1b31.png)
![screenshot_20160711-012427](https://cloud.githubusercontent.com/assets/20391839/16720763/706c14c4-4707-11e6-9a2e-ed7ff921f515.png)
![screenshot_20160711-012435](https://cloud.githubusercontent.com/assets/20391839/16720764/706cbe88-4707-11e6-924e-580e3eff8b22.png)
![screenshot_20160711-012441](https://cloud.githubusercontent.com/assets/20391839/16720762/7069487a-4707-11e6-81ec-69f1fc7ed7f1.png)

**Comment by cobalt232** [comment]
For unknown reason, Calendar and Contacts don't work on some devices. Try to install Google Calendar and Contact's and after that the BlackBerry versions.
