### ISSUE TITLE
Dialing from Blackberry Hub...

### ISSUE THREAD

**Issue by arthropod88** [cobalt232/blackberrymanager#62]
After the Pie update on my Samsung Note 9, I'm having a weird issue. If I click on a call from the list in Hub, it pops up details about the call. If I click the phone icon to dial that person, my phone one continually tries to call another number. No matter what item I click on hub call list, it will attempt to to call the same number. 

Also, if i try to send a text message from the Hub, it attempts to text the same wrong number.

Anyone else having this issue?

**Comment by cmy82** [comment]
I don't think that is an issue with BlackBerry Manager because I have the paid version of Hub and it dials the wrong number as well.

**Comment by cobalt232** [comment]
Definitely not a problem of BlackBerry Manager. Maybe report the issue on the Crackberry forum. The BlackBerry devs are reading there.
