### ISSUE TITLE
With the changes to SMS and Call list handling...

### ISSUE THREAD

**Issue by MyGreenBodhi** [cobalt232/blackberrymanager#63]
Is it possible to roll back to an earlier version of the Hub and Hub+ Services?
Where do I find them?

**Comment by Bobloblah** [comment]
Same question here. Absolutely kicking myself for not discovering the "backup" feature until after upgrading. Any help in rolling back would be greatly appreciated!

**Comment by Bobloblah** [comment]
Oh, and how do I donate to the development of these Android BlackBerry tools?

**Comment by cobalt232** [comment]
I'm sorry but I didn't create any backups either. You can ask some guys on Crackberry forums. I'm sure that some have a patched copy of the apps.

You can donate via PayPal. The link is in the about dialog of BlackBerry Manager.

**Comment by cmy82** [comment]
I have v 1.6.1.51155 of the Hub+ services and 1.6.1.15188 that are unpatched if those would work.

**Comment by Bobloblah** [comment]
I haven't been following the versions close enough to know... when are those from? Either way, I'd be grateful if you share them.

**Comment by cobalt232** [comment]
You can download older versions on APK Mirror and patch them using the new file patching feature in BlackBerry Manager (3 dots on top right).
