### ISSUE TITLE
Cannot answer texts in hub

### ISSUE THREAD

**Issue by caper66** [cobalt232/blackberrymanager#64]
When I select a text in the hub, it opens up the Samsung text app not the text message... is there a setting I am missing? This was not the case before the last upgrade, version 2.1902.0.16855 on Samsung galaxy s7

**Comment by cobalt232** [comment]
It's a change in the Hub+ suite where BlackBerry is following a new Google policy regarding access to sms and phone calls. I can't fix this on my side.
