### ISSUE TITLE
Blackeberry hub+ calendar and inbox - meeting 

### ISSUE THREAD

**Issue by stavrich** [cobalt232/blackberrymanager#65]
Blackeberry hub+ calendar and inbox
Phone - Sony xperia zx2 Android 9

The calendar is linked to a gmail account and all works fine. I can create a new meeting in the Blackberry Hub+ calendar and it will appear in the gmail calendar (and viewed via pc) and vice versa.

Problem, if I create a meeting via the Blackberry Hub+ Inbox – “Invite to meeting” I get the message “Calendar not selected”.

For my mails I have a pop3 account that I use. The gmail account is only used for the calendar.

If I add my pop account in the calendar as select it as the default then the “Invite to meeting” creates the meeting but is not created in the gmail calendar.

How can I get Inbox “Invite to meeting” to create the meeting the same way as creating it manually.

**Comment by cobalt232** [comment]
This seems to be a handling or application problem and is not related to BlackBerry Manager. Please visit Crackberry forum and post your question there.
