### ISSUE TITLE
BrickBreaker

### ISSUE THREAD

**Issue by notanewbie** [cobalt232/blackberrymanager#66]
Any plans to add BrickBreaker to the list of apps included in BlackBerry Manager?

**Comment by cobalt232** [comment]
Is there a BlackBerry version of that game available? What is the package name?

**Comment by notanewbie** [comment]
IIRC BrickBreaker is a game that comes with every BlackBerry phone, at least the pre-Android ones...

**Comment by cobalt232** [comment]
That App is not Android compatible, so nothing I can add to the manager. Sorry.
