### ISSUE TITLE
Blackberry Keyboard broken

### ISSUE THREAD

**Issue by sector1979** [cobalt232/blackberrymanager#68]
Blackberry Keyboard ( last signed from you ) it appears to be broken.   After downloading and installing trought Manager it doesn't appears more !!!

**Comment by cobalt232** [comment]
So what you are saying is that it is installed but you can't type with it? Did you activate it by taping the Keyboard icon in BlackBerry Manager?

**Comment by ForrestHerman** [comment]
I'm currently having the same or similar issue. I just upgraded my phone from Oreo to Pie via a factory reset and am in the process of setting everything back up.

With the blackberry keyboard installed and properly setup when I click in any textbox the keyboard just doesn't appear at all.

**Comment by cobalt232** [comment]
Blackberry stopped support for devices with older architectures. From BlackBerry Manager 1.0.0.58 on the keyboard us no longer selectable in the list of apps if the device doesn't meet architecture requirements.

**Comment by cobalt232** [comment]
Blackberry stopped support for devices with older architectures. From BlackBerry Manager 1.0.0.58 on the keyboard us no longer selectable in the list of apps if the device doesn't meet architecture requirements.
