### ISSUE TITLE
Keyboard crashes, won't function after update.

### ISSUE THREAD

**Issue by Kenshin1124** [cobalt232/blackberrymanager#69]
Sir, may I start by saying THANK YOU for the work you've done on this. I've been using the BlackBerry keyboard you made available to us on my LG K20+ for over a year now, and it's been so good to have BB's awesome keyboard back. Earlier today, I opened up BB Manager and it showed there was an update available for both Manager and Keyboard, so I went ahead and let it do both updates. Now every time I enable the BB Keyboard, it continually tells me that it has stopped, and that it keeps stopping, and forces me to close the app. I've had to go back to the LG keyboard, and I HATE it! If there's any way you can help me get my BB keyboard back, I'd very much appreciate it.

**Comment by cmy82** [comment]
Sorry, to hijack your thread. @cobalt232 I have an older version of your blackberry manager from maybe a year ago, along with the keyboard. I can send a link to you where I have them if you want, but it's 30+ MB for the keyboard so I can't link the file here.

**Comment by cobalt232** [comment]
Unfortunately, Blackberry had dropped native lib support for v7a instruction set (32 bit). So the new Keyboard v4.x no longer can work if your device is on 32 bit architecture. Only option is to use the latest v3.x version provided by BlackBerry Manager cloud repository. Tap Hamburger symbol to access the cloud repository.

**Comment by Kenshin1124** [comment]
Yes!!! Thank you so much! It's working again.

Sent via BlackBerry Hub+ Inbox for Android<http://play.google.com/store/apps/details?id=com.blackberry.hub>
