### ISSUE TITLE
Asking for hub + update as of late start version

### ISSUE THREAD

**Issue by MWZotti** [cobalt232/blackberrymanager#7]
I updated to the latest versions of the apps and now they all require hub + to be updated. 
![Uploading Screenshot_20160803-142504.png…]()

**Comment by AndrewL007** [comment]
Hi Cobalt, I'm in the same boat as MWZotti, had all of the BB apps installed perfectly on my Samsung S7 via your method (thanks!!), did the recent updates, and now I can't access any of them as all i get is the message 'Blackberry Hub+ needs to be updated'. Just wondering if you're planning to provide a way to bypass this or if we have to uninstall everything and start over again? cheers.

**Comment by rthill** [comment]
Same problem for me, tried already uninstalling the services, reboot an
install again, but problem persists.

**Comment by MWZotti** [comment]
Uninstall contacts and hub. Install using the repository files.   http://forums.crackberry.com/android-apps-f444/working-blackberry-priv-apps-any-android-device-no-root-required-1059855/

**Comment by cobalt232** [comment]
Fixed. Download the new version of BlackBerry Manager (1.0.0.24)

**Comment by mweags** [comment]
I am unable to download the manager I get a file that is very small and cannot be open
