### ISSUE TITLE
"Google Play connection error" when trying to check for updates

### ISSUE THREAD

**Issue by detsaoT** [cobalt232/blackberrymanager#72]
I am getting a connection error when I try checking for updates.  Running a Google Play Check-In does not seem to solve the problem.

**Comment by rayray519** [comment]
I'm seeing this as well on my S9+

**Comment by davidvaluja** [comment]
I have the same problem with Android 8 on Xperia XZ

**Comment by cobalt232** [comment]
Can you remove your Google account and add it again. Dies hat fix the issue?

**Comment by detsaoT** [comment]
I don't see a way to remove my Google account, but I went to the App Info page and cleared all app data. It prompted me to associate my account the next time I launched it. Still gives me the same error when it tries to refresh, though.

**Comment by detsaoT** [comment]
Thank you VERY much for making this app, by the way. This is the first thing I install on every Android device I've ever owned! You're a real lifesaver for all of us ex-Blackberry users that aren't the biggest fans of TCL. :)

**Comment by stohl** [comment]
S10e and the same problem...

**Comment by dtarin** [comment]
Note9 and S10+.  Same issue.

**Comment by Alaknar** [comment]
Sadly, I can also confirm the issue. Sony Xperia XZ1 Compact.

**Comment by dtarin** [comment]
I got it to work!  I closed the blackberry manager app and I just removed my associated Google account from my phone and added it right back.  

Upon starting BlackBerry Manager it asked a few setup questions and then worked fine after that.

**Comment by stohl** [comment]
So you just deleted the account generally from your system and added it afterwards? I would like to prevent to setup my phone again because of this.

**Comment by dtarin** [comment]
Yes.  I went into accoints in phone settings and removed it.  Then I added it right back before opening any other app.

 I thought the same but I personally didn't see much impact from doing that.  I dont use gmail or google services much and those apps that do just asked again to confirm which Google account to use and then taking me right back to where I left off.

YMMV

**Comment by dawnjc79** [comment]
This works, thank you!

**Comment by cintogia** [comment]
Worked. Thx.

**Comment by dtarin** [comment]
cool.  Glad we figured it out.   @detsaoT, this issue should be closed.

**Comment by davidvaluja** [comment]
Yesterday I tried to update the Cobalt BlackBerry Manager app, and all worked correctly. I have not done anything else. Just update and nothing else.  And all works fine.

**Comment by cobalt232** [comment]
This issue is fixed in BlackBerry Manager 1.0.0.58. 

The bulkDetails request that is used to fetch the list of updatable apps from Play Store doesn't return a HTTP_UNAUTHORIZED if the request is issued with an invalid token. A workaroud fixes this now.

**Comment by davidvaluja** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Thank you very much, Cobalt.                                                                                                                                       DAVID VALUJA FRAMIÑÁNbit.ly/DavidValujaF                                                                                                                                                                           De: notifications@github.comEnviado: 26 de octubre de 2019 17:46Para: blackberrymanager@noreply.github.comResponder a: reply@reply.github.comCc: dvaluja@gmail.com; comment@noreply.github.comAsunto: Re: [cobalt232/blackberrymanager] "Google Play connection error" when trying to check for updates (#72)  Closed #72.
