### ISSUE TITLE
cannot choose google account

### ISSUE THREAD

**Issue by dt12ps** [cobalt232/blackberrymanager#74]
Hi. I am hoping you can help me. I am stuck on choosing an account for Blackberry manager. If I choose one, the same window re-appears again and again. Tried unninstalling, signing off and on, nothing helps. 
Permissions have been granted by phone and by ADB as a troubleshooting step, nothing works. 

Android 8.1

**Comment by cobalt232** [comment]
Is this issue still open?

**Comment by cobalt232** [comment]
Remove your Google account from device and add it again. That should fix it.
