### ISSUE TITLE
BB keyboard on Moto G5 and G6

### ISSUE THREAD

**Issue by itcsm-net** [cobalt232/blackberrymanager#75]
Hello,
I've recently set up a couple Motorola phones for family members and found that the BlackBerry keyboard will not install properly on either G5 or G6 Motorola phones. When I try to choose it from the list of virtual keyboards, I get an error that states it can't be used to unlock the phone. Then it says 'BlackBerry keyboard has stopped.' I have tried going into the permissions from the App list and allowing them all, restarting the phone and attempting to choose the BlackBerry virtual keyboard again, with the same results. There is no third party security or Antivirus installed and it only happens on the Motorola phones. I just set up a Samsung and a Pixel with the same Android versions as the Motorola's and the keyboard installed and worked fine. In fact, this is the first time I've found any issues with the installation and use of of any of the BlackBerry features from your BlackBerry manager in the dozens of phones I've installed it on. (Great job and thank you!) Any ideas?

**Comment by cobalt232** [comment]
BlackBerry has decided to focus development on  arm64-v8a architecture. For that reason, the keyboard won't work anymore on older device types.
