### ISSUE TITLE
Please build a launcher

### ISSUE THREAD

**Issue by nicgentile** [cobalt232/blackberrymanager#78]
Selfish to ask, but I have been thumping around.

You know [Zinqs launcher](https://www.youtube.com/watch?v=VJurmqLaNC4)?

Well, I put up [this post](https://www.reddit.com/r/androidapps/comments/f5pe9k/can_i_pay_someone_to_update_an_app/) and then decided to ask. If we are able to do fundraising, are you able to build a BB10 like launcher with peek and flow? Asked about this [a few days ago ](https://www.reddit.com/r/blackberry/comments/f0l18h/what_is_the_equivalent_of_peek_and_flow_in_android/)that led me to your manager, so at the very least, I have to ask.

Thank you for making time.

**Comment by cobalt232** [comment]
Hi and thanks for your request. I'm not planning to develop a launcher for Android.
