### ISSUE TITLE
i can't install keyboard on samsung s8

### ISSUE THREAD

**Issue by derenato** [cobalt232/blackberrymanager#79]
could you help me install blackberry keyboard on samsung s8 please can't find option in blackberry manager

**Comment by derenato** [comment]
Hola ya pude instalarlo con éxito,  pero funciona muy bien con la versión que que esta en repositorio,  pero cuando actualiza a la última versión,  el teclado no es intuitivo y no predice palabras guardadas

**Comment by cobalt232** [comment]
It looks like you phone doesn't support arm64 v8a instruction set. That's why you don't see the keyboard in the list. Sorry to say, but you can only use keyboard up to version 3.4.x, as only this version is arm v7a compatible.

**Comment by derenato** [comment]
Muchas gracias por la respuesta, valoro mucho su trabajo.

**Comment by derenato** [comment]
Quisiera tener una opinión de un experto como usted. 
Sería bueno adquirir un BlackBerry Passport en estos tiempos?  

Me gusta el modelo pero no de tan amigable sea usarlo hoy en día. 
Ustedes como experto me podría dar una recomendación por favor?

**Comment by derenato** [comment]
I would like to have an opinion from an expert like you.
 Would it be good to acquire a BlackBerry passport in these times?

 I like the model but it is not so friendly to use it today.
 Could you as an expert please give me a recommendation?

**Comment by cobalt232** [comment]
Hi

I would not recommend to buy an OS10 BlackBerry these days. There are no new apps for OS10 and the implemented Android runtime is stuck on version 4.3, so less and less Android apps will work in near future

Better buy a Samsung S10  ;-)

Regards,
c



Gesendet mit der Bluewin App

Am 23 Mai 2020 um 19:40 schrieb derenato <notifications@github.com>:

**Comment by derenato** [comment]
Muchas gracias por su respuesta!  
Por ahora uso el teclado blackberry y realmente me conformo mucho con eso,  mil gracias por actualizarlos constantemente
