### ISSUE TITLE
Download problem 

### ISSUE THREAD

**Issue by mweags** [cobalt232/blackberrymanager#8]
I am unable to download I get a very small file that is unable to open

**Comment by cobalt232** [comment]
Downloaded from the downloads link. Don't try to right click/save the file from the file list.

**Comment by mweags** [comment]
I am downloading from there and is only 2.13mb and won't open. 

Thank you, 
Mike

**Comment by cobalt232** [comment]
That's the correct size. You need Android 6 or better to run the apps.

**Comment by mweags** [comment]
I am running 6.0 on LG V10 so I am not sure why I can't seem to open. Thank you, Mike                                                                                                                                                                         Sent via the BlackBerry Hub for Android                                                                                                                                                                                                                   From:notifications@github.comSent:August 4, 2016 2:12 AMTo:blackberrymanager@noreply.github.comReply-to:reply@reply.github.comCc:mweags@gmail.com; author@noreply.github.comSubject:Re: [cobalt232/blackberrymanager] Download problem (#8)  That's the correct size. You need Android 6 or better to run the apps.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
