### ISSUE TITLE
Keyboard Missing

### ISSUE THREAD

**Issue by littlejoeward** [cobalt232/blackberrymanager#81]
Sorry if this is the wrong place to do it but...

On my moto g6 the keyboard is missing. I tried looking at the repository but it says it password protected

**Comment by cobalt232** [comment]
Hi!

Here you go:
https://www.mycloud.ch/s/S00CA45C0C25631595529B19A9F57828D6517945CC2

Regards from Switzerland
C


Gesendet mit der Bluewin App

Am 30 Juni 2020 um 03:46 schrieb littlejoeward <notifications@github.com>:

**Comment by littlejoeward** [comment]
Thanks!
