### ISSUE TITLE
Apps installation issue

### ISSUE THREAD

**Issue by xpolymorph** [cobalt232/blackberrymanager#82]
Hi, 
I installed BlackBerry Manager and BlackBerry keyboard through BlackBerry manager. But for all the other apps, i constantly gel a message ''you need To install BlackBerry services'', Wen i try To install them.

I am using Xiaomi mi 9T, but my Phone does not support SD card. Is there and solution To install all the other  apps. I've been  a long user of BlackBerry so i need  these apps in my Phone. Thanks  in advance.

**Comment by cobalt232** [comment]
Well, did you install BlackBerry Hub+ Services? It's an app listed in the Manager. You need that component to run all other BlackBerry apps.

**Comment by xpolymorph** [comment]
Thank you for your quick answer.
When  i try To install BlackBerry Hub+ services, BlackBerry manager downloads  the app, star the installation but at the fais To installe it.

On the other and, Wen i tried To install BlackBerry hub+ services through Play Store i worked flawlessly and all thé ôter apps appears in the lister apps i can install. But i suppose thaï if i continue with thé other BlackBerry hub+ services it won't .be possible To patch them once installed.

I am using Android Pie and Miui 10.

Do you have a solution for me , please ?

**Comment by cobalt232** [comment]
If installation of Hub+ Services fails, the most common error is, that you still have BlackBerry apps installed from another source (i.e Play Store). Remove all BlackBerry apps and double check that they are gone.

**Comment by xpolymorph** [comment]
Ok i try  it and let you know.

**Comment by xpolymorph** [comment]
Back again  for good news. Nothing else To say but thank  you VERY Much. I Forgot to remove Calendar I had installed through Play store. Thank you very much. 
I want to mentione that I already used your work 
to sideload my BlackBerry Passport. Again thank you. 

One last thing. I want To restore my credentials I had saved in my Google drive with Google play version of Password Keeper, but it is not possible to restore them with the new Password Keeper. Any idea to solve those inconvenience ???

**Comment by xpolymorph** [comment]
I solved my issue about restoring saved pwd with Password Keeper installed through Play store. I first re-installed Passport Keeper through Play Store, restored saved credentials, exported them to my Goggle drive account and finally installed Password Keeper with BB Manager and restored credentials. I retrieved all my saved data. 

@cobalt232, This solution worked but i think a fix is needed to sync previous account with Password keeper.

**Comment by cobalt232** [comment]
The solution you describe is the suggested one. The patched apps can't sync with Google Drive because of the altered signature. For obvious reasons, I didn't implement an alternative Google Drive syncing method based on my signatures, as that would be a security risk for the users.

**Comment by xpolymorph** [comment]
Ok. thank for your help and for all that you have done for bb community.
👏

**Comment by cobalt232** [comment]
Thank you! Closing.
