### ISSUE TITLE
latest version permissions on android 6.0 (contacts and phone)

### ISSUE THREAD

**Issue by mike-pt** [cobalt232/blackberrymanager#9]
Is this expected / needed?

This permissions are not described in the Readme and it doesnt seem like the app would need them.

acesso to storage is also requested but that's understandable as it needs to download apks.

**Comment by cobalt232** [comment]
Both permissions are required to check-in your device as a BlackBerry device at the Google Servers. The app won't work without those permissions.

**Comment by mystica555** [comment]
Can you please in detail explain how 'contacts' is required for this?  I do not want my address book leaking out to random places... I can understand other permissions but not Contacts.

**Comment by cobalt232** [comment]
BlackBerry Manager needs the "contacts" permission to read two tokens from your primary Google Account on the device. The following tokens are fetched:

- ac2dm
- androidmarket

These tokens are needed to checking as a mocked BlackBerry Device and to authenticate with Google Play.

That's it.
